export type VerifiedFireFleet={vehicles:string[];source:string;verifiedAt:string};

const source="https://alt.bfv-imst.at/feuerwehren";
const verifiedAt="2026-08-22";
const fleet=(vehicles:string[]):VerifiedFireFleet=>({vehicles,source,verifiedAt});

// Öffentlich gelistete Fuhrparks des Bezirksfeuerwehrverbandes Imst.
export const verifiedFireFleets:Record<string,VerifiedFireFleet>={
 "Innsbruck":{vehicles:["KDO","KDO 2","ELF","ELF 2","TLF-A 3000/500 Gruppe 1","TLF-A 3000/500 Gruppe 2","TLF-A 2000 Trupp","ULF","THF","GSF","KÖF","HRB","DLK 37","KF 45","WAF-A","TEF","HTF","FEF","MTF 1","MTF 2","MTF 3","MTF 4","TF 1","TF 2","TF 3","LAST 1","LAST 2"],source:"https://www.feuerwehr-innsbruck.at/feuerwehren/berufsfeuerwehr/",verifiedAt},
 "Hall":{vehicles:["KDO","TLF 1 2000","TLF 2 3000/100","DLK 23/12","SRF","WLF 1","WLF 2","LAST","MTF","Schmutzwasserpumpe","KAT-Anhänger","AB Körperschutz","AB Wasser","AB Gefahrgut","AB Bau","AB Sand"],source:"https://feuerwehr-hall.at/de/fahrzeuge/",verifiedAt},
 "Telfs":{vehicles:["KDOFA","MZFA","TLFA 3000/100 Tank 1","SRF","DLK 23/12","TLFA 3000/100 Tank 2","LFB-A","MTF","LAST-A","GGF","Stromaggregat-Anhänger","LFBA-W","BLF"],source:"https://www.feuerwehr-telfs.at/fahrzeuge/",verifiedAt},
 "Kitzbühel":{vehicles:["KDO 1","KDO 2","RLF-A","DLK 23/12","TLF-A","LFB-A","SRF-A","GGF","LAST","MZF-A","MTF-A","Stromaggregat 80"],source:"https://www.feuerwehr-kitz.at/technik/fahrzeuge",verifiedAt},
 "Kufstein":{vehicles:["KDO","TLFA 3000/100","TLF 3000/100","SLFA","DLK 37","SRF","KRFS","GGF","LAST 1","LAST 2","LAST 3","MTF 1","MTF 2","Lader"],source:"https://feuerwehr-kufstein.at/?page_id=544",verifiedAt},
 "Landeck":{vehicles:["KDO-A","RLF-T 3000 Tunnel 1","RLF-T 3000 Tunnel 2","TLFA 2000","LF-A Pumpe 1","DLK 23/12","SRF","WLF-K","KÖF","LAST 1","KLF-A Pumpe 2","LAST 2","MTF-A","Hubsteiger","LUF 60","Stromaggregat 80","AB Gefahrgut","AB Pritsche"],source:"https://www.feuerwehr-landeck.at/fahrzeuge/",verifiedAt},
 "Lienz":{vehicles:["KDOFA 1","KDOFA 2","MTFA","LAST","GGF","SRF","TANK 1","TANK 2","PUMPE 1","PUMPE 2","ASF","DLK"],source:"https://www.feuerwehr-lienz.at/index.php/ausruestung/fahrzeuge",verifiedAt},
 "Reutte":{vehicles:["KDO","SRF","DLK 23/12","TLFA 1","TLFA 2","LFA","GGF-A","MTF-A","LAST 1","LAST 2","Arbeitsboot"],source:"https://feuerwehr-reutte.at/fuhrpark/",verifiedAt},
 "Arzl i. P.":fleet(["KDO","LAST über 3,5 t","TLFA 2000","LFB-A"]),
 "Gurgl":fleet(["KDO","LFB-A","TLF-A 3000"]),
 "Haiming":fleet(["MTF","RF","TLFA 3000/200","LFB-A"]),
 "Haimingerberg":fleet(["KLF"]),
 "Huben i. Ö.":fleet(["KLF","TLF 1500"]),
 "Imst":{vehicles:["KDOFA 1","KDOFA 2","MTF","LFBA","TLFA 1 3000/100","TLFA 2 3000/200","RLF-T 3000/200","DLK 30","SRF","GGF","LAST 1","LAST 2","Stapler"],source:"https://www.ff-imst.at/Ausruestung",verifiedAt},
 "Imsterberg":fleet(["KDO","KLF","TLF 1500"]),
 "Jerzens":fleet(["KLF","LAST bis 3,5 t","LF-A","RLF-A 2000"]),
 "Karres":fleet(["TLF-A 1500","KLF"]),
 "Karrösten":fleet(["KDO","LFB","TLF-A 1500"]),
 "Längenfeld":fleet(["KDO","RF","KLF","LF 1","LF 2","LAST über 3,5 t","TLF-A 3000"]),
 "Leins":fleet(["KLF-A"]),
 "Mieming":fleet(["KDO-A","LAST bis 3,5 t","LFB-A","MTF","TLF-A 3000"]),
 "Mils b.I.":fleet(["KLF-A","TLF 1500"]),
 "Mötz":fleet(["MTF-A","LFB","TLF 2000"]),
 "Nassereith":fleet(["KDO-A","KLF","LAST über 3,5 t","LFB-A","RLF-A 2000"]),
 "Neurur":fleet(["KLF"]),
 "Niederthai":fleet(["KLF","TLF 2000"]),
 "Obsteig":fleet(["KLF","LAST bis 3,5 t","TLF-A 2000"]),
 "Ochsengarten":fleet(["LFB-A"]),
 "Ötz":fleet(["KLF","LAST bis 3,5 t","LFB-A","TLF-A 3000"]),
 "Ötzerau":fleet(["KLF","TLF-A 1500"]),
 "Ötztal-Bahnhof":fleet(["KLF","TLF 1500"]),
 "Plangeroß":fleet(["KLF","TLF-A 1500"]),
 "Rietz":fleet(["KDO","MTF","LFA","RLF-A 200","Schlauchboot 1","Schlauchboot 2"]),
 "Roppen":fleet(["KDO","LAST über 3,5 t","LFB","TLF-A 2000"]),
 "Sautens":fleet(["KDO-A","KLF-A","LFB-A","RLF-A 2000/200"]),
 "Silz":fleet(["KRF-S","MTF-A 1","MTF-A 2","KLF","TLFA 3000/200","RLF-T 3000/200","SRF","DL 30","TLFA 1500","LAST-A über 3,5 t"]),
 "Sölden":fleet(["DL 30","KDO-A","LAST über 3,5 t","SLF","TLF-A 2000","TLFA 1500","RFA"]),
 "St. Leonhard (Innerpitztal)":fleet(["DL 30","LFB-A","TLF-A 3000/200"]),
 "Stams":fleet(["KLF","LF","MTF","TLF-A 2000/200"]),
 "Tarrenz":fleet(["KLF","MTF","LFB-A","TLF-A 2000 1","TLF-A 2000 2"]),
 "Tumpen":fleet(["LFB"]),
 "Umhausen":fleet(["KLF","LFB-A","MTF-A","TLF-A 3000/200"]),
 "Vent":fleet(["LAST-A","TLF-A 3000"]),
 "Wald":fleet(["LFB-A-W"]),
 "Wenns":fleet(["LF","MTF-A","RF","TLF-A 2000"]),
 "Zaunhof":fleet(["KLF","TLF 1500"]),
};
